name: Test Output Overflow Layered Deepest
on:
  workflow_dispatch:
jobs:
  big-output:
    uses: ./.github/workflows/test-overflow-middle.yaml
  downstream:
    needs: big-output
    runs-on: ubuntu-latest
    steps:
      - run: echo "I ran"
